import { useState } from "react";
import React from 'react'
import { SafeAreaView } from "react-native-safe-area-context";
import { Image, Text, View } from "react-native";
import { ScrollView } from "react-native-gesture-handler";

import CustomButton from "../../components/CustomButton";
import { images, icons } from "../../constants";

const dummyMessages = [
  {
    role: 'VirtualTherapyBot',
    content: 'Welcome back, <Patient Username>! I am your virtual therapy assistant Stacy.'
  },
  {
    role: 'VirtualTherapyBot',
    content: 'Please select the following practice task to get started on your therapy session.'
  },
  {
    role: 'Patient',
    content: 'Hello, how are you? I am fine thank you.'
  },
  {
    role: 'VirtualTherapyBot',
    content: 'I am fine too thank you for asking! Please select the following practice task to get started on your therapy session.'
  },
  {
    role: 'VirtualTherapyBot',
    content: 'https'
  },
  {
    role: 'Patient',
    content: 'Woah!'
  }
]

const chatbot = ( {initialMessages = dummyMessages } ) => {
  const [message, setMessages] = useState(initialMessages);
  const [isRecording, setIsRecording] = useState(false);

  const toggleRecording = async () => {
    setIsRecording(prevState => !prevState);
  };

  return (
    <View className="flex-1 bg-white">
      <SafeAreaView className="flex-1 flex mx-5 mb-5">
        {
          message.length > 0? (
          <View className="space-y-2 flex-1">
            <View className="bg-neutral-200 rounded-3xl p-4">
              <ScrollView
                className="space-y-4"
                showsVerticalScrollIndicator={false}
                bounces={false}>
                {
                  message.map((message, index) => {
                    if (message.role == "VirtualTherapyBot") {
                      if (message.content.includes('https')) {
                        // Image Generated by the Chatbot
                        return (
                          <View key={index} className="flex-row justify-start items-start">
                            {/* Chatbot Icon */}
                            <Image className="rounded-full"
                              source={icons.chatbot}
                              style={{ height: 32, width: 32, marginRight: 8 }}
                            />
  
                            {/* Chatbot Image Message Bubble */}
                            <View className="p-2 flex rounded-2xl bg-blue-200 rounded-tl-none">
                              <Image
                                source={images.cycling}
                                className="rounded-2xl"
                                resizeMode="contain"
                                style={{height: 160, width: 160}}
                                />
                            </View>
                        </View>
                        )
                      } else {
                        // Chatbot Response
                        return (
                          <View key={index} className="flex-row justify-start items-start">
                            {/* Chatbot Icon */}
                            <Image className="rounded-full"
                              source={icons.chatbot}
                              style={{ height: 32, width: 32, marginRight: 8 }}
                            />
                            
                            {/* Chatbot Message Bubble */}
                            <View key={index} className="bg-blue-200 rounded-xl p-2 rounded-tl-none flex-1">
                              <Text>{message.content}</Text>
                            </View>
                          </View>
                        )
                      }
                    } else {
                      // Patient Input
                      return (
                        // Patient Message Bubble
                        <View
                          key={index}
                          className="bg-white rounded-xl p-2 rounded-tr-none ml-16">
                          <Text>{message.content}</Text>
                        </View>
                      )
                    }
                  })
                }
              </ScrollView>
            </View>
          </View>

          ): (
            <></>
          )
        }
        {/* Recording Button */}
        <View className="flex justify-center items-center">
          <CustomButton
            title={isRecording ? "Recording..." : "Tap to start recording"}
            handlePress={toggleRecording}
            backgroundColor={isRecording ? "#d55e00" : "#0072B2"}
            containerStyles={[{ width: '100%' }, { marginTop: 14 }]}
            isLoading={isRecording}
          />
        </View>
      </SafeAreaView>
    </View>
  )
}

export default chatbot