import { StatusBar } from 'expo-status-bar';
import { Audio } from "expo-av";
import React, { useState, useRef, useEffect } from 'react';
import { Image, Text, View, FlatList, ListRenderItem, StyleSheet, Platform, Pressable} from "react-native";
import { Ionicons } from '@expo/vector-icons';

import ErrorModal from "../../components/ErrorModal";
import { images, icons } from "../../constants";
import { useAuthContext } from '../../context/AuthContext';

// Define types for messages
type Message = {
  role: 'Bot' | 'Patient';
  content: string;
};

const dummyMessages: Message[] = [
  {
    role: 'Bot',
    content: 'Great! Let us start with the first question! What is the boy doing?'
  },
  {
    role: 'Bot',
    content: 'https'
  },
  {
    role: 'Patient',
    content: 'Cycling'
  }
  
];

const Chatbot: React.FC<{ initialMessages?: Message[] }> = ({ initialMessages = dummyMessages }) => {
  const { appUser } = useAuthContext();
  const [ username ] = useState(appUser?.username);

  const [errorModalVisible, setErrorModalVisible] = useState(false);
  const [errorHeaderMessage, setErrorHeaderMessage] = useState('');
  const [errorMessage, setErrorMessage] = useState('');

  // Task
  const [ taskSelected, isTaskSelected ] = useState(false);
  const [ isSubmittingTask, setSubmittingTask ] = useState(false);

  const startTask = async(selectedTask: string) => {
    setSubmittingTask(true);

    if (selectedTask.length == 0) {
      setErrorHeaderMessage("MISSING_TASK")
      setErrorMessage("Please select a task.")
      setErrorModalVisible(true);
      setSubmittingTask(false);
    }
    else {
      try {
        // Send POST request for patient login
        // Use ipconfig to find ip address of your pc/emulator in the local network
        const response = await fetch('http://192.168.1.97:44818/api/patient/create-task', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            username: selectedTask,
          }),
        });

        const jsonResponse = await response.json();

        if (response.ok) {
          isTaskSelected(true);
        } else {
          // Handle errors
          setErrorHeaderMessage(jsonResponse.status)
          setErrorMessage(jsonResponse.message)
          setErrorModalVisible(true);
        }
      } catch (error) {
        console.error('Error:', error);
        if (error instanceof TypeError) { // Error such as Network request failed
          setErrorHeaderMessage("NETWORK REQUEST TIMED_OUT")
          setErrorMessage("There was a problem with the network request.")
          setErrorModalVisible(true);
        }    
      } finally {
        setSubmittingTask(false);
      }
    }
  }

  // Message History
  const [ messages, setMessages ] = useState<Message[]>(initialMessages);
  const [loading, setLoading] = useState(false);
  const maxMessages = 200; // Maximum number of messages to keep in memory
  const flatListRef = useRef<FlatList<Message>>(null);

  useEffect(() => {
    // Scroll to the bottom when messages change
    if (flatListRef.current) {
      flatListRef.current.scrollToEnd({ animated: true });
    }
  }, [messages]);

  const renderMessage: ListRenderItem<Message> = ({ item, index }) => {
    if (item.role === "Bot") {
      if (item.content.includes('https')) {
        // Image Generated by the Chatbot
        return (
          <View key={index} className="flex-row justify-start items-start mt-3">
            {/* Chatbot Icon */}
            <Image
              className="w-9 h-9 rounded-full border-2 mr-2 border-gray-200 dark:border-white"
              source={icons.chatbot}
            />
            {/* Chatbot Image Message Bubble */}
            <View className="p-2 flex rounded-2xl bg-gray-200 dark:bg-gray-600">
              <Image
                source={images.cycling}
                className="rounded-xl"
                resizeMode="contain"
                style={{ height: 256, width: 256 }}
              />
            </View>
          </View>
        );
      } else {
        // Chatbot Response
        return (
          <View key={index} className="flex-row justify-start items-start mt-3">
            {/* Chatbot Icon */}
            <Image
              className="w-9 h-9 rounded-full border-2 mr-2 border-gray-200 dark:border-white"
              source={icons.chatbot}
            />
            {/* Chatbot Message Bubble */}
            <View className="rounded-xl p-2 flex-1 bg-gray-200 dark:bg-gray-600">
              <Text className='text-base text-dark dark:text-light'>{item.content}</Text>
            </View>
          </View>
        );
      }
    } else {
      // Patient Input
      return (
        // Patient Message Bubble
        <View key={index} className="rounded-xl p-2 ml-20 mt-3 bg-blue-500 dark:bg-blue-600">
          <Text className='text-base text-light'>{item.content}</Text>
        </View>
      );
    }
  };

  // Recording
  const [ isRecording, setIsRecording ] = useState(false);
  const [ recording, setRecording ] = useState<Audio.Recording | undefined>(undefined);
  const [ permissionResponse, requestPermission ] = Audio.usePermissions();

  const startRecording = async () => {
    try {
      if (!permissionResponse || permissionResponse.status !== 'granted') {
        console.log('Requesting permission..');
        await requestPermission();
      }
      await Audio.setAudioModeAsync({
        allowsRecordingIOS: true,
        playsInSilentModeIOS: true,
      });

      console.log('Starting recording..');
      const { recording } = await Audio.Recording.createAsync( Audio.RecordingOptionsPresets.HIGH_QUALITY);
      setRecording(recording);

      console.log('Recording started');
      setIsRecording(true)
    } catch (err) {
      console.error('Failed to start recording', err);
    }
  };

  const stopRecording = async () => {
    try {
      if (recording) {
        console.log('Stopping recording..');
        await recording.stopAndUnloadAsync();
        setRecording(undefined);

        await Audio.setAudioModeAsync({
          allowsRecordingIOS: false,
        });

        const uri = recording.getURI();
        console.log('Recording stopped and stored at', uri);
        setIsRecording(false)

        // Send uri to backend

      } else {
        console.log('No recording to stop');
      }
    } catch (err) {
      console.error('Failed to stop recording', err);
    }
  }

  useEffect(() => {
    // Cleanup function to stop the recording when the component unmounts
    return () => {
      if (recording) {
        stopRecording(); // You need to implement stopRecording function to stop and cleanup the recording
      }
    };
  }, [recording]);

  return (
    <View className="flex-1 bg-light dark:bg-dark">
      <ErrorModal 
        headerMessage={errorHeaderMessage}
        errorMessage={errorMessage}
        modalVisible={errorModalVisible}
        setModalVisible={setErrorModalVisible}
      />

      {messages.length > 0 ? (
        <View className="px-3 mb-6">
          {
            !taskSelected ? (
              // Chatbot Task Message
              <View className="flex-row justify-start items-start mt-3">
                <Image
                  className="w-9 h-9 rounded-full border-2 mr-2 border-gray-200 dark:border-white"
                  source={icons.chatbot}
                />
                <View className="rounded-xl p-2 flex-1 bg-gray-200 dark:bg-gray-600">
                  <Text className='text-base text-dark dark:text-light'>Welcome back, {username}! I am your personal virtual therapy assistant Stacy. Please select a task below to get started.</Text>
                  {/* List of Task */}
                  <View className='m-2'>
                    <Pressable style={({ pressed }) => [, pressed ? { opacity: 0.5 } : {},]} 
                        onPress={() => {
                            startTask("Word Retrieval Task");
                          }
                        }>
                      <View className="rounded-tr-xl rounded-tl-xl flex-row items-center p-3 bg-gray-200 dark:bg-blue-600">
                        <Ionicons name="reader" size={24} color='#fff'/>
                        <Text className='ml-2 text-base text-dark dark:text-light'>Word Retrieval Task</Text>
                      </View>
                    </Pressable>
                    <Pressable style={({ pressed }) => [, pressed ? { opacity: 0.5 } : {},]} 
                        onPress={() => {
                            // startTask("Sentence Completion Task");
                          }
                        }>
                      <View className="p-3 flex-row items-center bg-gray-200 dark:bg-blue-600">
                        <Ionicons name="reader" size={24} color='#fff'/>
                        <Text className='ml-2 text-base text-dark dark:text-light'>Sentence Completion Task</Text>
                      </View>
                    </Pressable>
                    <Pressable style={({ pressed }) => [, pressed ? { opacity: 0.5 } : {},]} 
                        onPress={() => {
                            // startTask("Article Reading Task");
                          }
                        }>
                      <View className="rounded-br-xl rounded-bl-xl flex-row items-center p-3 bg-gray-200 dark:bg-blue-600">
                        <Ionicons name="reader" size={24} color='#fff'/>
                        <Text className='ml-2 text-base text-dark dark:text-light'>Article Reading Task</Text>
                      </View>
                    </Pressable>
                  </View>
                </View>
              </View>
            ) : (
              <FlatList
                data={messages}
                renderItem={renderMessage}
                keyExtractor={(item, index) => index.toString()}
                // onEndReached={loadMoreMessages} // Load more messages when end is reached
                onEndReachedThreshold={0.1} // Load more when 10% from the bottom
                showsVerticalScrollIndicator={false}
                ref={flatListRef}
                onContentSizeChange={() => flatListRef.current?.scrollToEnd({ animated: true })}
                contentContainerStyle={styles.flatListContent}
              />
            )
          }
        </View>
      ) : (
        <View className='flex-1'></View>
      )}

      { taskSelected ? (
        // Recording Button
        <View className={`absolute bottom-0 left-0 right-0 justify-center items-center pt-1 ${Platform.OS === 'ios' ? 'py-5' : 'py-2'} bg-light dark:bg-dark`}>
        <Text className='text-base text-light'>{isRecording ? "Recording..." : "Tap to start recording"}</Text>
          {
            isRecording ? (
              <Pressable
                style={({ pressed }) => [,
                  pressed ? { opacity: 0.5 } : {},
                ]} 
                onPress={
                  stopRecording
                }>
                <Ionicons name="pause-circle" size={96} color="#d55e00"/>
              </Pressable>
            ) : (
              <Pressable
                style={({ pressed }) => [,
                  pressed ? { opacity: 0.5 } : {},
                ]} 
                onPress={ 
                  startRecording
                }>
                <Ionicons name="radio-button-on" size={96} color="#d55e00"/>
              </Pressable>
            )
          }
      </View>
      ) : (
        <View className='flex-1'></View>
      )}

    </View>
  );
};

export default Chatbot;

const styles = StyleSheet.create({
  flatListContent: {
    paddingHorizontal: 4,
    paddingBottom: 128, // Ensure some space at the bottom for the overlay button
  },
});