import { StatusBar } from 'expo-status-bar';
import React, { useState, useRef, useEffect } from 'react';
import { SafeAreaView } from "react-native-safe-area-context";
import { Image, Text, View, FlatList, ListRenderItem } from "react-native";

import CustomButton from "../../components/CustomButton";
import { images, icons } from "../../constants";

// Define types for messages
type Message = {
  role: 'VirtualTherapyBot' | 'Patient';
  content: string;
};

const dummyMessages: Message[] = [
  {
    role: 'VirtualTherapyBot',
    content: 'Welcome back, <Patient Username>! I am your virtual therapy assistant Stacy.'
  },
  {
    role: 'VirtualTherapyBot',
    content: 'Please select the following practice task to get started on your therapy session.'
  },
  {
    role: 'Patient',
    content: 'Hello, how are you? I am fine thank you.'
  },
  {
    role: 'VirtualTherapyBot',
    content: 'I am fine too thank you for asking! Please select the following practice task to get started on your therapy session.'
  },
  {
    role: 'VirtualTherapyBot',
    content: 'https'
  },
  {
    role: 'Patient',
    content: 'Woah!'
  }
  ,
  {
    role: 'Patient',
    content: 'Hello'
  }
  
];

const Chatbot: React.FC<{ initialMessages?: Message[] }> = ({ initialMessages = dummyMessages }) => {
  const [messages, setMessages] = useState<Message[]>(initialMessages);
  const [isRecording, setIsRecording] = useState(false);
  const flatListRef = useRef<FlatList<Message>>(null);

  const toggleRecording = async () => {
    setIsRecording(prevState => !prevState);
  };

  useEffect(() => {
    // Scroll to the bottom when messages change
    if (flatListRef.current) {
      flatListRef.current.scrollToEnd({ animated: true });
    }
  }, [messages]);

  const renderItem: ListRenderItem<Message> = ({ item, index }) => {
    if (item.role === "VirtualTherapyBot") {
      if (item.content.includes('https')) {
        // Image Generated by the Chatbot
        return (
          <View key={index} className="flex-row justify-start items-start mb-3">
            {/* Chatbot Icon */}
            <Image
              className="rounded-full"
              source={icons.chatbot}
              style={{ height: 32, width: 32, marginRight: 8 }}
            />
            {/* Chatbot Image Message Bubble */}
            <View className="p-2 flex rounded-2xl rounded-tl-none bg-gray-200 dark:bg-gray-600">
              <Image
                source={images.cycling}
                className="rounded-2xl"
                resizeMode="contain"
                style={{ height: 160, width: 160 }}
              />
            </View>
          </View>
        );
      } else {
        // Chatbot Response
        return (
          <View key={index} className="flex-row justify-start items-start mb-3">
            {/* Chatbot Icon */}
            <Image
              className="rounded-full"
              source={icons.chatbot}
              style={{ height: 32, width: 32, marginRight: 8 }}
            />
            {/* Chatbot Message Bubble */}
            <View className="rounded-xl p-2 rounded-tl-none flex-1 bg-gray-200 dark:bg-gray-600">
              <Text className='text-dark dark:text-light'>{item.content}</Text>
            </View>
          </View>
        );
      }
    } else {
      // Patient Input
      return (
        // Patient Message Bubble
        <View key={index} className="rounded-xl p-2 rounded-tr-none ml-16 mb-3 bg-blue-500 dark:bg-blue-600">
          <Text className='text-light'>{item.content}</Text>
        </View>
      );
    }
  };

  return (
    <View className="flex-1 flex-shrink flex-grow py-4 px-4 bg-light dark:bg-dark">
      <SafeAreaView className="rounded-lg bg-light dark:bg-black">
        {messages.length > 0 ? (
          <View className="px-3">
            <FlatList
              data={messages}
              renderItem={renderItem}
              keyExtractor={(item, index) => index.toString()}
              showsVerticalScrollIndicator={false}
              ref={flatListRef}
              onContentSizeChange={() => flatListRef.current?.scrollToEnd({ animated: true })}
            />
          </View>
        ) : (
          <></>
        )}
      </SafeAreaView>

      {/* Recording Button */}
      <View className="flex justify-center items-center">
        <CustomButton
          title={isRecording ? "Recording..." : "Tap to start recording"}
          handlePress={toggleRecording}
          backgroundColor={isRecording ? "#d55e00" : "#0072B2"}
          containerStyles={[{ width: '100%' }, { marginTop: 14 }]}
          isLoading={isRecording}
        />
      </View>
    </View>
  );
};

export default Chatbot;
